# Generated by Django 5.0.4 on 2024-04-29 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be at least 8 characters long and contain at least one uppercase letter.', regex='^(?=.*[A-Z]).{8,}$')]),
        ),
    ]
