# Generated by Django 5.0.4 on 2024-05-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
