# Generated by Django 5.0.4 on 2024-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.TextField(max_length=250),
        ),
    ]
