version: '3.7'

services:
    redis:
        image: redis:alpine
        container_name: redis-online-shop
        networks:
          - live

    backend:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
        - "5000:8000"
        environment:
        - REDIS_HOST=redis
        networks:
          - live
networks:
  live:



#version: '3.7'
#
#services:
##  db:
##    image: postgres:12-alpine
##    restart: always
##    volumes:
##      - db-data:/var/lib/postgresql/data
##    networks:
##      - live
#
#  redis:
#    image: 'redis:alpine'
#    hostname: redis
#    networks:
#      - live
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    hostname: app
#    stdin_open: true
#    expose:
#      - '8000'
#
#    command: bash -c "python manage.py migrate && gunicorn myproject.wsgi:application -b 0.0.0.0:8000"
#    depends_on:
#      - redis
#    networks:
#      - live
#
##volumes:
##  db-data:
#
##networks:
##  live:
