# Generated by Django 5.0.4 on 2024-04-17 15:50

import core.utils
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=functools.partial(core.utils.maker, *('<django.db.models.fields.related.ForeignKey>',), **{}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'gif', 'mp4', 'avi', 'flv'])]),
        ),
    ]
