# Generated by Django 5.0.4 on 2024-04-17 15:51

import core.utils
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=functools.partial(core.utils.maker, *("<class 'django.db.models.fields.PositiveIntegerField'>",), **{}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg', 'gif', 'mp4', 'avi', 'flv'])]),
        ),
    ]
