# Generated by Django 5.0.4 on 2024-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_discountcode_alter_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
