# Generated by Django 5.0.4 on 2024-06-10 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.PositiveIntegerField(max_length=16)),
                ('cvv2', models.PositiveIntegerField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d{3,4}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
